theme = 'catppuccin_mocha'

[editor]
line-number = 'relative'
cursorline = true
color-modes = true
insert-final-newline = false
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = 'all'
end-of-line-diagnostics = 'hint'
continue-comments = false
scrolloff= 10

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ['spinner', 'version-control', 'file-name', 'file-modification-indicator']

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal.space]
w = { w = ":w", q = ":wq" }
x = ':q!'
n = ':open ~/Files/Shine.docs/' # Replace with your notes folder path

[keys.normal]
F5 = ':config-reload'
q = ':buffer-close'

[keys.insert]
j = {k = 'normal_mode'}
