theme = 'catppuccin_mocha'

[editor]
line-number = 'relative'
cursorline = true
color-modes = true
insert-final-newline = false
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = 'all'
end-of-line-diagnostics = 'hint'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ['spinner', 'version-control', 'file-name', 'file-modification-indicator']

[keys.normal.space]
w = { w = ":w", q = ":wq" }
x = ':q!'

[keys.normal]
F5 = ':config-reload'
q = ':buffer-close'

[keys.insert]
j = {k = 'normal_mode'}
