[[language]]
name = "markdown"
language-servers = [ "marksman" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

## Biome Js
[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

# Typescript
[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.vtsls.config]
hostInfo = "helix"

[[language]]
name = "typescript"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "biome" ]
auto-format = true
