require('modules.keymaps')
require('modules.autostart')
require('modules.input')
require('modules.enviroment')
require('modules.appearance')
require('modules.animations')
require('modules.rules')
hl.config({ autogenerated = false }) -- remove this line to remove the warning
